motor:
  max_peak_rpm: 6500
  max_continuous_rpm: 5500

  max_continous_current: 180.0   
  max_peak_current: 360.0       

  max_continous_power: 64000.0  
  max_peak_power: 124000.0      

  max_continous_torque: 112.0
  max_peak_torque: 220.0

  kt_constant: 0.7     # Nm / A  Used to convert current to torque (and vice versa) (slighly lower than datasheet as the motor is used with less voltage)
  peak_duration: 120.0   # seconds 
  
  efficiency_map:
    500:
      10: 0.87
      20: 0.88
      40: 0.90
      60: 0.91
      80: 0.90
      100: 0.89

    1000:
      10: 0.88
      20: 0.89
      40: 0.92
      60: 0.93
      80: 0.92
      100: 0.91

    1500:
      10: 0.89
      20: 0.90
      40: 0.93
      60: 0.95
      80: 0.95
      100: 0.94
      120: 0.93

    2000:
      10: 0.89
      20: 0.90
      40: 0.94
      60: 0.95
      80: 0.96
      100: 0.96
      120: 0.95

    2500:
      10: 0.89
      20: 0.91
      40: 0.94
      60: 0.96
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    3000:
      10: 0.88
      20: 0.91
      40: 0.94
      60: 0.96
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    3500:
      10: 0.88
      20: 0.90
      40: 0.93
      60: 0.95
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    4000:
      10: 0.87
      20: 0.89
      40: 0.92
      60: 0.94
      80: 0.95
      100: 0.95
      120: 0.94
      140: 0.93

    4500:
      10: 0.87
      20: 0.88
      40: 0.91
      60: 0.93
      80: 0.94
      100: 0.94
      120: 0.93
      140: 0.92

    5000:
      10: 0.86
      20: 0.88
      40: 0.90
      60: 0.92
      80: 0.93
      100: 0.93
      120: 0.92

    5500:
      10: 0.86
      20: 0.87
      40: 0.89
      60: 0.91
      80: 0.92
      100: 0.92