motor:
  max_peak_rpm: 6500
  max_continuous_rpm: 5500

  max_continuous_current: 160.0
  max_peak_current: 340.0
  peak_duration: 5.0   # seconds (datasheet says: "few seconds")

  torque_speed_continuous:
    0: 102
    500: 102
    1000: 102
    1500: 102
    2000: 102
    2500: 102
    3000: 102
    3500: 102
    4000: 102
    4500: 102
    5000: 102
    5250: 97
    5500: 92

  torque_speed_peak:
    0: 230
    500: 230
    1000: 230
    1500: 230
    2000: 230
    2500: 230
    3000: 230
    3500: 230
    4000: 215
    4500: 200
    5000: 185
    5500: 170
    6000: 150
    6500: 130

  efficiency_map:
    500:
      10: 0.87
      20: 0.88
      40: 0.90
      60: 0.91
      80: 0.90
      100: 0.89

    1000:
      10: 0.88
      20: 0.89
      40: 0.92
      60: 0.93
      80: 0.92
      100: 0.91

    1500:
      10: 0.89
      20: 0.90
      40: 0.93
      60: 0.95
      80: 0.95
      100: 0.94
      120: 0.93

    2000:
      10: 0.89
      20: 0.90
      40: 0.94
      60: 0.95
      80: 0.96
      100: 0.96
      120: 0.95

    2500:
      10: 0.89
      20: 0.91
      40: 0.94
      60: 0.96
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    3000:
      10: 0.88
      20: 0.91
      40: 0.94
      60: 0.96
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    3500:
      10: 0.88
      20: 0.90
      40: 0.93
      60: 0.95
      80: 0.96
      100: 0.96
      120: 0.95
      140: 0.94

    4000:
      10: 0.87
      20: 0.89
      40: 0.92
      60: 0.94
      80: 0.95
      100: 0.95
      120: 0.94
      140: 0.93

    4500:
      10: 0.87
      20: 0.88
      40: 0.91
      60: 0.93
      80: 0.94
      100: 0.94
      120: 0.93
      140: 0.92

    5000:
      10: 0.86
      20: 0.88
      40: 0.90
      60: 0.92
      80: 0.93
      100: 0.93
      120: 0.92

    5500:
      10: 0.86
      20: 0.87
      40: 0.89
      60: 0.91
      80: 0.92
      100: 0.92