battery:
  # Este valores s√£o postas random, preciso falar com eletro para os valores reais
  nominal_voltage: 600.0
  capacity_ah: 60.0 
  max_continuous_discharge_current: 250.0
  max_peak_discharge_current: 400.0
  internal_resistance: 0.01
  peak_duration: 30.0
  soc_voltage_map:
    "1.0": 600.0
    "0.9": 595.0
    "0.8": 590.0
    "0.7": 585.0
    "0.6": 580.0
    "0.5": 570.0
    "0.4": 560.0
    "0.3": 555.0
    "0.2": 550.0
    "0.1": 540.0
    "0.0": 530.0
  min_voltage: 320.0
  max_voltage: 600.0
  min_soc: 0.05