tire_model:
  name: "complex_pacejka"

  #Valores que estavam na struct como default, faltam os dados reais
  camber_scaling_factor: 1.0
  effective_tire_r: 1.0
  distance_to_CG: 1.0  # Positivo se a roda estiver à frente do CG, negativo se atrás

  d_bright: 1.06
  d_bleft: 1.06
  d_fright: 0.99
  d_fleft: 0.99
  camber: 0
  dimension:
    UNLOADED_RADIUS: 0.235
    WIDTH: 0.2159
    ASPECT_RATIO: 0.55
    RIM_RADIUS: 0.1905
    RIM_WIDTH: 0.152

  operating_conditions:
    INFLPRES: 220000
    NOMPRES: 220000

  inertia:
    MASS: 17.451
    IXX: 0.4
    IYY: 0.7
    BELT_MASS: 7
    BELT_IXX: 0.34
    BELT_IYY: 0.6
    GRAVITY: -9.81

  vertical:
    FNOMIN: 1113.5001
    VERTICAL_STIFFNESS: 200000
    VERTICAL_DAMPING: 50
    MC_CONTOUR_A: 0.5
    MC_CONTOUR_B: 0.5
    BREFF: 8.4
    DREFF: 0.27
    FREFF: 0.07
    Q_RE0: 1
    Q_V1: 0
    Q_V2: 0
    Q_FZ2: 0.0001
    Q_FCX: 0
    Q_FCY: 0
    Q_CAM: 0
    PFZ1: 0.88241
    Q_FCY2: -0.4751
    Q_CAM1: 85.19
    Q_CAM2: 257.4
    Q_CAM3: 0.5119
    Q_FYS1: -20496.4
    Q_FYS2: -60000
    Q_FYS3: 88211.7
    BOTTOM_OFFST: 0.01
    BOTTOM_STIFF: 2000000

  structural:
    LONGITUDINAL_STIFFNESS: 300000
    LATERAL_STIFFNESS: 100000
    YAW_STIFFNESS: 5000
    FREQ_LONG: 80
    FREQ_LAT: 40
    FREQ_YAW: 50
    FREQ_WINDUP: 70
    DAMP_LONG: 0.04
    DAMP_LAT: 0.04
    DAMP_YAW: 0.04
    DAMP_WINDUP: 0.04
    DAMP_RESIDUAL: 0.002
    DAMP_VLOW: 0.001
    Q_BVX: 0
    Q_BVT: 0
    PCFX1: 0
    PCFX2: 0
    PCFX3: 0
    PCFY1: 0
    PCFY2: 0
    PCFY3: 0
    PCMZ1: 0

  contact_patch:
    Q_RA1: 0.5
    Q_RA2: 1
    Q_RB1: 1
    Q_RB2: -1
    ELLIPS_SHIFT: 0.8
    ELLIPS_LENGTH: 1
    ELLIPS_HEIGHT: 1
    ELLIPS_ORDER: 1.8
    ELLIPS_MAX_STEP: 0.025
    ELLIPS_NWIDTH: 10
    ELLIPS_NLENGTH: 10

  inflation_pressure_range:
    PRESMIN: 10000
    PRESMAX: 1000000

  vertical_force_range:
    FZMIN: 228.6
    FZMAX: 1600

  long_slip_range:
    KPUMIN: -0.25
    KPUMAX: 0.25

  slip_angle_range:
    ALPMIN: -0.2094
    ALPMAX: 0.2094

  inclination_angle_range:
    CAMMIN: -0.1047
    CAMMAX: 0.1047

  scaling_coefficients:
    LFZO: 1
    LCX: 1
    LMUX: 1
    LEX: 1
    LKX: 1
    LHX: 0
    LVX: 0
    LCY: 1
    LMUY: 1
    LEY: 1
    LKY: 1
    LHY: 0
    LVY: 0
    LTR: 1
    LRES: 0
    LXAL: 1
    LYKA: 1
    LVYKA: 1
    LS: 1
    LKYC: 1
    LKZC: 1
    LVMX: 0
    LMX: 1
    LMY: 1
    LMP: 1

  longitudinal_coefficients:
    PCX1: 1.786
    PDX1: 2.933
    PDX2: -0.44
    PDX3: 20.8
    PEX1: 0.871
    PEX2: -0.038
    PEX3: 0
    PEX4: 0.071
    PKX1: 85.31
    PKX2: -20.25
    PKX3: 0.5
    PHX1: 0
    PHX2: 0
    PVX1: 0
    PVX2: 0
    PPX1: 0
    PPX2: 0
    PPX3: 0
    PPX4: 0
    RBX1: 23.72
    RBX2: 25.97
    RBX3: 0
    RCX1: 0.7495
    REX1: -0.4759
    REX2: 0.8109
    RHX1: 0

  overturning_coefficients:
    QSX1: 0
    QSX2: 0
    QSX3: 0
    QSX4: 5
    QSX5: 1
    QSX6: 10
    QSX7: 0
    QSX8: 0
    QSX9: 0.4
    QSX10: 0
    QSX11: 5
    QSX12: 0
    QSX13: 0
    QSX14: 0
    PPMX1: 0

  lateral_coefficients:
    PCY1: 1.6384
    PDY1: 2.3749
    PDY2: -0.1985
    PDY3: 4.0072
    PEY1: 0.53284
    PEY2: -0.33312
    PEY3: 0.27748
    PEY4: -0.016493
    PEY5: 0
    PKY1: -38.9068
    PKY2: 1.6336
    PKY3: 0.62971
    PKY4: 2
    PKY5: 0
    PKY6: -1
    PKY7: 0
    PHY1: -4.3588e-16
    PHY2: -2.2117e-17
    PVY1: 9.4249e-16
    PVY2: 3.9982e-18
    PVY3: -3.2711
    PVY4: -1.1442
    PPY1: 0
    PPY2: 0
    PPY3: 0
    PPY4: 0
    PPY5: 0
    RBY1: 20.33
    RBY2: 8.152
    RBY3: -0.01243
    RBY4: 0
    RCY1: 0.9317
    REY1: -0.0003982
    REY2: 0.3077
    RHY1: 1.3384e-17
    RHY2: 1.352e-17
    RVY1: 2.0035e-17
    RVY2: -1.3167e-17
    RVY3: 2.2302e-18
    RVY4: -6.7562e-18
    RVY5: 7.583e-18
    RVY6: 2.0886e-17

  rolling_coefficients:
    QSY1: -0.0309
    QSY2: -0.0921
    QSY3: 0
    QSY4: 0
    QSY5: 0
    QSY6: 0
    QSY7: 0.85
    QSY8: -0.4

  aligning_coefficients:
    QBZ1: 10
    QBZ2: 0
    QBZ3: 0
    QBZ4: 0
    QBZ5: 0
    QBZ9: 10
    QBZ10: 0
    QCZ1: 1.1
    QDZ1: 0.12
    QDZ2: 0
    QDZ3: 0
    QDZ4: 0
    QDZ6: 0
    QDZ7: 0
    QDZ8: -0.05
    QDZ9: 0
    QDZ10: 0
    QDZ11: 0
    QEZ1: 0
    QEZ2: 0
    QEZ3: 0
    QEZ4: 0
    QEZ5: 0
    QHZ1: 0
    QHZ2: 0
    QHZ3: 0
    QHZ4: 0
    PPZ1: 0
    PPZ2: 0
    SSZ1: 0
    SSZ2: 0
    SSZ3: 0
    SSZ4: 0

    # POSTA DO CHAT ATE TER DADOS DE VD
  turnslip_coefficients:
    PECP1: 0.8
    PECP2: 0.1
    PDXP1: 0.5
    PDXP2: 0.0
    PDXP3: 1.0
    PDXP4: 0.0
    PDYP1: 1.0
    PDYP2: 0.1
    PDYP3: 1.0
    PDYP4: 0.0
    PKYP1: 35
    PHYP1: 0.2
    PHYP2: 0.1
    PHYP3: 0.3
    PHYP4: 0.0

  # Other configuration numbers
  configurations:
    Amu: 1.0
