perception:
  ransac_epsilon: 0.02
  ransac_iterations: 20
  ransac_n_neighbours: 15
  fov_trim_angle: 60.0
  pc_max_range: 30.0
  pc_min_range: 1.0
  pc_rlidar_max_height: -0.20
  clustering_n_neighbours: 1
  clustering_epsilon: 0.3
  horizontal_resolution: 0.2
  vertical_resolution: 0.33
  ground_removal: "ransac"
  n_angular_grids: 12
  radius_resolution: 5.0
  target_file: "cone.pcd"
  max_correspondence_distance: 0.1
  max_iteration: 100
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 1e-6
  min_height: -100.0
  large_max_height: 150.0
  small_max_height: 100.0
  height_cap: 0.5
  min_xoy: -100.0
  max_xoy: 100.0
  min_z: -100.0
  max_z: 100.0
  out_distance_cap: 0.5
  min_distance_x: 0.02
  min_distance_y: 0.04
  min_distance_z: 0.07
  min_n_points: 4
  min_confidence: 0.90
  height_out_weight: 0.15
  height_in_weight: 0.10
  cylinder_radius_weight: 0.2
  cylinder_height_weight: 0.10
  cylinder_npoints_weight: 0.05
  npoints_weight: 0.2
  displacement_x_weight: 0.03
  displacement_y_weight: 0.04
  displacement_z_weight: 0.04
  deviation_xoy_weight: 0.07
  deviation_z_weight: 0.07