perception:
  ransac_epsilon: 0.06
  ransac_iterations: 20
  ransac_n_neighbours: 20
  fov_trim_angle: 35.0
  pc_max_range: 12.0
  pc_min_range: 1.0
  pc_rlidar_max_height: -0.20
  clustering_n_neighbours: 3
  clustering_epsilon: 0.1
  horizontal_resolution: 0.33
  vertical_resolution: 0.2
  ground_removal: "grid_ransac"
  n_angular_grids: 8
  radius_resolution: 20.0
  target_file: "cone.pcd"
  max_correspondence_distance: 0.1
  max_iteration: 100
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 1e-6
  min_height: 0.1
  large_max_height: 0.55
  small_max_height: 0.4
  height_cap: 0.5
  min_xoy: 0.0
  max_xoy: 0.3
  min_z: 0.00001
  max_z: 0.6
  min_z_score_x: 0.45
  max_z_score_x: 1.55
  min_z_score_y: 0.45
  max_z_score_y: 1.55
  out_distance_cap: 0.5
  min_distance_x: 0.02
  min_distance_y: 0.04
  min_distance_z: 0.07
  min_n_points: 4
  min_confidence: 0.90
  height_out_weight: 0.15
  height_in_weight: 0.10
  cylinder_radius_weight: 0.2
  cylinder_height_weight: 0.10
  cylinder_npoints_weight: 0.05
  npoints_weight: 0.2
  displacement_x_weight: 0.03
  displacement_y_weight: 0.04
  displacement_z_weight: 0.04
  deviation_xoy_weight: 0.07
  deviation_z_weight: 0.07