perception:
  ransac_epsilon: 0.06
  ransac_n_neighbours: 20
  fov_trim: 35.0
  pc_max_range: 12.0
  clustering_n_neighbours: 3
  clustering_epsilon: 0.1
  horizontal_resolution: 0.33
  vertical_resolution: 0.2
  ground_removal: "grid_ransac"
  n_angular_grids: 8
  radius_resolution: 20.0
  target_file: "cone.pcd"
  max_correspondence_distance: 0.1
  max_iteration: 100
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 1e-6
  min_height: 0.1
  max_height: 0.55
  min_xoy: 0.0
  max_xoy: 0.3
  min_z: 0.00001
  max_z: 0.6
  min_z_score_x: 0.45
  max_z_score_x: 1.55
  min_z_score_y: 0.45
  max_z_score_y: 1.55
