perception:
  default_mission: "trackdrive"

  #Publishers
  publish_fov_trimmed_cloud: false
  publish_ground_removed_cloud: false
  publish_wall_removed_cloud: true

  #LiDAR Parameters
  lidar_height: 1.10
  lidar_horizontal_resolution: 0.2
  lidar_vertical_resolution: 0.33

  #FOV trimming
  apply_rotation: false
  rotation: 90.0
  apply_fov_trimming: false
  fov: 180.0    #ATTENTION: If fov trimming not applied, leave at 180 degrees
  min_range: 2.0
  max_height: 3.0

  #TRACKDRIVE/AUTOCROSS TRIMMING
  max_range: 40.0

  #ACCELERATION TRIMMING
  acc_max_range: 40.0
  acc_max_y: 3.5

  #SKIDPAD TRIMMING
  skid_max_range: 40.0

  #Ground Grid
  ground_grid_range: 40.0  #ATTENTION: Should be >= all max_ranges
  ground_grid_angle: 4.5
  ground_grid_radius: 1.0
  ground_grid_start_augmentation: 15.0
  ground_grid_radius_augmentation: 0.10

  #Ground Removal
  ground_removal: "himmelsbach"  #options: "ransac", "himmelsbach"
  ransac_epsilon: 0.15
  ransac_iterations: 40
  himmelsbach_grid_angle: 2.0
  himmelsbach_max_slope: 1.00
  himmelsbach_initial_alpha: 1.50
  himmelsbach_alpha_augmentation_m: 0.35
  himmelsbach_start_augmentation: 12.0

  #Wall Removal
  wall_removal_grid_angle: 4.5
  wall_removal_grid_radius: 0.35
  wall_removal_start_augmentation: 12.0
  wall_removal_radius_augmentation: 0.07
  wall_removal_max_points_per_cluster: 100
  
  #Clustering
  clustering: "GridClustering"  #options: "GridClustering", DBSCAN not done yet
  DBSCAN_n_neighbours: 1
  DBSCAN_clustering_epsilon: 0.32
  grid_clustering_grid_angle: 0.5
  grid_clustering_grid_radius: 0.07
  grid_clustering_start_augmentation: 15.0
  grid_clustering_radius_augmentation: 0.005

  #Evaluator
  small_cone_width: 0.25
  large_cone_width: 0.30
  small_cone_height: 0.35
  large_cone_height: 0.55
  n_out_points_ratio: 0.20
  max_distance_from_ground_min: 0.50 # max distance from the ground of the lowest point in the cluster
  max_distance_from_ground_max: 0.90 # max distance form the ground of the highest point in the cluster
  n_points_intial_max: 50
  n_points_intial_min: 4
  n_points_max_distance_reduction: 1.5
  n_points_min_distance_reduction: 0.15

  #ICP
  target_file: "cone.pcd"
  max_correspondence_distance: 0.1
  max_iteration: 100
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 1e-6
  
