perception:

  horizontal_resolution: 0.33
  vertical_resolution: 0.2
  default_mission: "trackdrive"

  #FOV trimming
  lidar_height: 0.92
  lidar_rotation: 90.0
  lidar_pitch: -3.90
  min_range: 1.0
  max_height: 0.7

    #TRACKDRIVE/AUTOCROSS TRIMMING
  max_range: 30.0
  fov_trim_angle: 45.0

    #ACCELERATION TRIMMING
  acc_max_range: 20.25
  acc_fov_trim_angle: 90.0
  acc_max_y: 2.5

    #SKIDPAD TRIMMING
  skid_max_range: 20.25
  skid_min_distance_to_cone: 2.3
  
  #Ground Removal
  ground_removal: "grid_ransac"
  ransac_epsilon: 0.13
  ransac_iterations: 100

    #TRACKDRIVE/AUTOCROSS GROUND REMOVAL
  n_angular_grids: 4
  radius_resolution: 7.5

    #ACCELERATION GROUND REMOVAL
  acc_n_angular_grids: 2
  acc_radius_resolution: 7.5

    #SKIDPAD GROUND REMOVAL
  skid_n_angular_grids: 2
  skid_radius_resolution: 7.5


  #Clustering
  clustering_n_neighbours: 1
  clustering_epsilon: 0.5

  #Evaluator
  min_height: 0.15
  large_max_height: 0.57
  small_max_height: 0.42
  height_cap: 0.5
  min_xoy: 0.0
  max_xoy: 0.3
  min_z: 0.00001
  max_z: 0.6
  min_z_score_x: -100000000.0
  max_z_score_x: 100000000000.0
  min_z_score_y: -1000000000.0
  max_z_score_y: 1000000000.0
  out_distance_cap: 0.5
  min_distance_x: 0.02
  min_distance_y: 0.04
  min_distance_z: 0.11
  min_n_points: 4
  min_confidence: 0.912
  height_out_weight: 12.0
  height_in_weight: 5.0
  cylinder_radius_weight: 20.0
  cylinder_height_weight: 8.0
  cylinder_npoints_weight: 10.0
  npoints_weight: 11.0
  displacement_x_weight: 7.0
  displacement_y_weight: 8.0
  displacement_z_weight: 10.5
  deviation_xoy_weight: 10.0
  deviation_z_weight: 10.0

  #ICP
  target_file: "cone.pcd"
  max_correspondence_distance: 0.1
  max_iteration: 100
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 1e-6

  