planning: 
  # ---------------------- Midpoint Generator (mg_) ----------------------
  mg_minimum_cone_distance: 2.0 #  The rules say 3m, but we should keep it lower for safety
  mg_maximum_cone_distance: 10.0 
  mg_sliding_window_radius: 40.0
  #---------------------- Path Calculation (pc_) ------------------------
  pc_use_sliding_window: false
  pc_angle_gain: 70.0  
  pc_distance_gain: 6.0
  pc_angle_exponent: 2.0
  pc_distance_exponent: 1.0
  pc_max_cost: 100.0
  pc_lookback_points: 4
  pc_search_depth: 4
  pc_max_points: 200
  pc_minimum_point_distance: 1.0
  pc_reset_interval: 1000000000
  pc_use_reset_path: false
  #---------------------- Skidpad (skidpad_) ------------------
  skidpad_minimum_cones: 10
  skidpad_tolerance: 5
  #---------------------- Path Smoothing (smoothing_) -------------------
  smoothing_spline_precision: 10
  smoothing_spline_order: 3
  smoothing_spline_coeffs_ratio: 3.0
  smoothing_min_path_point_distance: 0
  smoothing_use_path_smoothing: true
  smoothing_use_optimization: true
  smoothing_car_width: 1.2
  smoothing_safety_margin: 0.3
  smoothing_curvature_weight: 100.0
  smoothing_smoothness_weight: 0.1
  smoothing_safety_weight: 1000000
  smoothing_max_iterations: 4000
  smoothing_tolerance: 1e-5     
  #---------------------- Velocity Planning (vp_) -----------------------
  vp_minimum_velocity: 2.0
  vp_braking_acceleration: -3.0
  vp_acceleration: 4.0
  vp_lateral_acceleration: 3.0
  vp_use_velocity_planning: true
  vp_desired_velocity: 20.0
  #---------------------- Planning Config (planning_) ---------------------------
  planning_publishing_visualization_msgs: true
  planning_using_full_map: true