global:
  adapter: "vehicle" # "vehicle" or "pacsim" or...
  car_config: "02" # default car configuration to load from config/car/
  vehicle_frame_id: "map" # "map" or ... -> frame_id for the visualization messages
  use_simulated_se: false # use simulated state estimator from the simulator
  use_simulated_perception: false # use simulated perception from the simulator
  use_simulated_planning: false # use simulated planning from the mocker_node
  use_simulated_velocities: false # use simulated velocities from the simulator
  discipline: "autocross"  # Options: "autocross", "skidpad", "acceleration"
  track_name: "FSG23"
  vehicle_frame_id: "map" # "map" or ... -> frame_id for the visualization messages