global:
  adapter: "pacsim" # "vehicle" or "pacsim" or...
  config_name: "" # version of the configuration, appended to the adapter name on the file name e.g. "_faster_control"
  use_simulated_se: true # use simulated state estimator from the simulator
  use_simulated_perception: false # use simulated perception from the simulator
  use_simulated_planning: false # use simulated planning from the mocker_node
  use_simulated_velocities: true # use simulated velocities from the simulator
  track_name: "FSG23"
  vehicle_frame_id: "map" # "map" or ... -> frame_id for the visualization messages