global:
  adapter: "vehicle" # "vehicle" or "pacsim" or...
  config_name: "" # version of the configuration, appended to the adapter name on the file name e.g. "_faster_control"
  use_simulated_se: true # use simulated state estimator from the simulator
  use_simulated_perception: false # use simulated perception from the simulator
  use_simulated_planning: false # use simulated planning from the mocker_node
  use_simulated_velocities: false # use simulated velocities from the simulator
  track_name: "FSG24"
  vehicle_frame_id: "vehicle_state" # "vehicle_state" or ... -> frame_id for the visualization messages TODO: fix this
