invictasim:
  # Simulator config
  vehicle_model: "FSFEUP02"  # Options: "FSFEUP02"
  timestep: 0.001  # seconds (0.001s = 1000 Hz)
  use_simulated_se: false # use simulated state estimator from the simulator
  use_simulated_perception: false # use simulated perception from the simulator
  use_simulated_planning: false # use simulated planning from the mocker_node
  use_simulated_velocities: false # use simulated velocities from the simulator
  simulation_speed: 1.0 # 1.0 = real-time, >1.0 faster, <1.0 slower
  discipline: "autocross"  # Options: "autocross", "skidpad", "acceleration"
  track_name: "FSG23"