vehicle_model:
  name: "bicycle"

  car_parameters: "02"

  aero_model: "simple_aero"
  aero_model_params: "simple_aero"

  tire_model: "pacejka"
  tire_model_params: "complex_pacejka"

  motor_model: "map_based_motor"
  motor_model_params: "map_based_motor"

  load_transfer_model: "simple_load_transfer"
  load_transfer_model_params: "simple_load_transfer"

  steering_motor_model: "simple_steering_motor"
  steering_motor_model_params: "simple_steering_motor"
  