vehicle_model:
  name: "fsfeup02"

  car_parameters: "02"

  aero_model: "default_aero"
  aero_model_params: "simple_aero"

  tire_model: "pacejka_MF6_2"
  tire_model_params: "complex_pacejka"

  motor_model: "map_based_motor"
  motor_model_params: "motor"

  battery_model: "thevenin"
  battery_model_params: "battery"

  differential_model: "viscous_lsd"
  differential_model_params: "differential"

  load_transfer_model: "vd_model" # Options: "rigid_body_model", "vd_model"
  load_transfer_model_params: "load_transfer"

  steering_motor_model: "simple_steering_motor"
  steering_motor_model_params: "simple_steering_motor"
  