velocity_estimation:
  estimation_method: "ekf"
  wheel_speed_noise: 0.1
  motor_rpm_noise: 0.1
  steering_angle_noise: 0.0001
  imu_acceleration_noise: 0.05
  imu_rotational_noise: 0.001
  wheel_base: 1.6
  weight_distribution_front: 0.5
  gear_ratio: 4.0
  wheel_radius: 0.129
