velocity_estimation:
  estimation_method: "ekf"
  s2v_model_name: "bicycle_model"
  process_model_name: "ca_particle_model"
  wheel_speed_noise: 0.7
  motor_rpm_noise: 0.7
  steering_angle_noise: 0.1
  imu_acceleration_noise: 0.1
  imu_rotational_noise: 0.1
  angular_velocity_process_noise: 0.1