# Parameter set for KITTI odometry dataset
# If this config doesn't work stably in your env., please refer to parameter tuning guide in README.md

# topic: /velodyne_points (set in launch file or command line)
deskew: false
max_range: 100.0
min_range: 5.0
voxel_size: 0.6
desired_num_voxelized_points: 3000
planarity_threshold: 0.18
max_points_per_voxel: 3
initial_threshold: 2.0
min_motion_th: 0.1
max_num_iterations: 100
convergence_criterion: 0.0001