vehicle_model:
  simple_bicycle_model:
    kinematics:
      lr: 0.804
      lf: 0.726
      sf: 1.2
      sr: 1.2
    tire:
      Blat: 9.63
      Clat: -1.39
      Dlat: 1.6
      Elat: 1.0
    aero:
      cla: 0.86
      cda: 0.73
      aeroArea: 0.44
    m: 200.707
    Izz: 101.082
    wheelRadius: 0.203
    gearRatio: 4.0
    innerSteeringRatio: 0.1869
    outerSteeringRatio: 0.1582
    nominalVoltageTS: 600.0
    powerGroundForce: 0.0
    # powertrainEfficiency: 0.95